set_property PACKAGE_PIN G7 [get_ports R]
set_property PACKAGE_PIN F8 [get_ports G]
set_property PACKAGE_PIN AC19 [get_ports clk]
set_property PACKAGE_PIN Y3 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports G]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property IOSTANDARD LVCMOS33 [get_ports reset]


set_property IOSTANDARD LVCMOS33 [get_ports {manual_state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {manual_state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports manual_override]
set_property PACKAGE_PIN AC21 [get_ports manual_override]
set_property PACKAGE_PIN AD24 [get_ports {manual_state[1]}]
set_property PACKAGE_PIN AC22 [get_ports {manual_state[0]}]
