set_property PACKAGE_PIN G7 [get_ports R]
set_property PACKAGE_PIN F8 [get_ports G]
set_property PACKAGE_PIN AC19 [get_ports clk]
set_property PACKAGE_PIN Y3 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports G]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports R]
set_property IOSTANDARD LVCMOS33 [get_ports reset]


set_property IOSTANDARD LVCMOS33 [get_ports {manual_state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {manual_state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports manual_override]
set_property PACKAGE_PIN AC21 [get_ports manual_override]
set_property PACKAGE_PIN AD24 [get_ports {manual_state[1]}]
set_property PACKAGE_PIN AC22 [get_ports {manual_state[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {time_remaining[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {time_remaining[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {time_remaining[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {time_remaining[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN C4 [get_ports {seg[7]}]
set_property PACKAGE_PIN A2 [get_ports {seg[6]}]
set_property PACKAGE_PIN D4 [get_ports {seg[5]}]
set_property PACKAGE_PIN E5 [get_ports {seg[4]}]
set_property PACKAGE_PIN B4 [get_ports {seg[3]}]
set_property PACKAGE_PIN B2 [get_ports {seg[2]}]
set_property PACKAGE_PIN E6 [get_ports {seg[1]}]
set_property PACKAGE_PIN C3 [get_ports {seg[0]}]
set_property PACKAGE_PIN H7 [get_ports {time_remaining[3]}]
set_property PACKAGE_PIN D5 [get_ports {time_remaining[2]}]
set_property PACKAGE_PIN A3 [get_ports {time_remaining[1]}]
set_property PACKAGE_PIN A5 [get_ports {time_remaining[0]}]
